name: Image build on event for Jetson Testing

on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]
  workflow_dispatch:
#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:

    runs-on: ubuntu-20.04
    
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      matrix:
        TESTING: [testing]
        TARGET: [jetson-nano-2gb-bionic] # <-- Add targets here!

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
    - name: Setup env
      run: |
        echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
    
    
    ### ONLY THIS RELEVANT FOR BUILDING ###    
    - name: spaceleft
      run: sudo df -h
    - uses: actions/checkout@v2
    - name: update
      run: sudo apt-get update
    - name: dep
      run: sudo apt-get install unzip curl git qemu qemu-user-static binfmt-support
    - name: configure
      run: sudo ./build.sh ${{ matrix.TARGET }} ${{ matrix.TESTING }} small
    - name: listdata
      run: sudo ls
    - name: see space left1
      run: sudo df -h
    - name: delete workdir
      run: sudo rm -Rf -v /home/runner/work/Open.HD_Image_Builder/Open.HD_Image_Builder/work-jetson-nano-2gb-bionic/*
    - name: see if there is enough space for uploading
      run: sudo df -h

    ########################################


    - name: Compose release filename
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      run: echo "artifact_name=OpenHD-image-${{ matrix.TARGET }}-${{ matrix.TESTING }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" >> $GITHUB_ENV
        
    - name: Pack image for ${{ matrix.TARGET }} ${{ matrix.TESTING }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: "${{ env.artifact_name }}"
        path: |
          ./deploy/*.img
          if-no-files-found: error
