name: Image Build on Event

on:
  push:
   branches:
      - "sdk"
      - "dev-release"
      - "release"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Maximize Build Space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 100
        swap-size-mb: 200
        remove-dotnet: true
        remove-android: true
        remove-haskell: true
        remove-codeql: true
        remove-docker-images: true
        overprovision-lvm: true

    - name: Check out code
      uses: actions/checkout@v4

    - name: Install Dependencies and Download SDK
      run: |
        sudo apt update
        sudo apt install -y python2 build-essential bc device-tree-compiler libmpc-dev bison expect expect-dev
        sudo apt install -y git rsync gcc g++ make device-tree-compiler bc flex bison lz4 libssl-dev libgmp-dev libmpc-dev expect expect-dev file unzip bzip2 fakeroot bsdmainutils
    #     wget -q https://fra1.digitaloceanspaces.com/openhd-images/BaseImages/rk356x_linux5.10_rkr8_sdk.repo.tar
    #     tar -xvf rk356x_linux5.10_rkr8_sdk.repo.tar
    #     .repo/repo/repo sync -l -j1 --fail-fast
    
    - name: Run Build Script
      run: |
        chmod +x scripts/sdk_builder.sh
        # Use whichever platform config you want; e.g., 'rock3', 'rpi', etc.
        # This must match your br_<PLATFORM>.conf in /images
        ./scripts/sdk_builder.sh luckfox_picoA
    # - name: Add Radxa Configuration
    #   run: |
    #     cd device/rockchip
    #     git remote add radxa https://github.com/radxa/device-rockchip.git
    #     git fetch radxa
    #     git checkout -b rk3566_rk3568-linux-5.10 remotes/radxa/rk3566_rk3568-linux-5.10

    # - name: Add Radxa Kernel
    #   run: |
    #     cd kernel
    #     git remote add openhd https://github.com/openhd/linux-rock.git
    #     git fetch openhd
    #     git checkout -b radxa-buildroot remotes/openhd/radxa-buildroot
    
    # - name: Apply Makefile Patch for Wifi
    #   run: |
    #     cd kernel
    #     patch -p1 < patches/openhd_wifi.patch
    
    # - name: Compile Image
    #   run: |
    #     echo "rockchip_rk3566_radxa_zero_3w_defconfig" | ./build.sh

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: compiled-image
        path: buildroot/output/image/*