name: Build_OpenHD_Beast_Module

on: [push]

jobs:
  download-file:
    runs-on: ubuntu-20.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 100
          swap-size-mb: 200
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          overprovision-lvm: 'true'
      - name: remove even more
        run: |
            sudo apt-get purge -y \
              '^llvm-.*' \
              'php.*' \
              '^mongodb-.*' \
              '^mysql-.*' \
              azure-cli \
              google-chrome-stable \
              firefox \
              powershell \
              microsoft-edge-stable \
              mono-devel
            sudo apt-get autoremove -y
            sudo apt-get clean
      - name: Download file from Sciebo
        env:
          SCIEBO_USERNAME: ${{ secrets.SCIEBO_USERNAME }}
          SCIEBO_PASSWORD: ${{ secrets.SCIEBO_PASSWORD }}
          SCIEBO_URL: ${{ secrets.SCIEBO_URL }}
        run: |
          echo "Downloading file from Sciebo..."
          curl -u "$SCIEBO_USERNAME:$SCIEBO_PASSWORD" -O "$SCIEBO_URL/remote.php/webdav/openhd/openhd/rk3566_SDK/repo_build_test.gz"
          echo "Download complete."
          sudo tar -xvpf repo_build_test.gz -C /
          ls -a
          ls -a /opt
          cd /opt
          sudo apt update
          sudo apt install liblz4-tool python2 git rsync gcc g++ make device-tree-compiler bc flex bison lz4 libssl-dev libgmp-dev libmpc-dev expect expect-dev file unzip bzip2 fakeroot bsdmainutils
          sudo ln -s /bin/python2 /bin/python
          rm -rf tspi_linux_sdk_repo_20240131.tar
          ./build.sh all
