name: Build_OpenHD_Beast_Module

on: [push]

jobs:
  download-file:
    runs-on: ubuntu-latest

    steps:
      - name: Download file from Sciebo
        env:
          SCIEBO_USERNAME: ${{ secrets.SCIEBO_USERNAME }}
          SCIEBO_PASSWORD: ${{ secrets.SCIEBO_PASSWORD }}
          SCIEBO_URL: ${{ secrets.SCIEBO_URL }}
        run: |
          echo "Downloading file from Sciebo..."
          curl -u "$SCIEBO_USERNAME:$SCIEBO_PASSWORD" -O "$SCIEBO_URL/remote.php/webdav/openhd/openhd/rk3566_SDK/repo_build_test.gz"
          echo "Download complete."
          sudo tar -xzvpf repo_build_test.gz -C /
          ls -a
          ls -a /opt

