name: Image build on event

on:
  push:

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      matrix:
        TARGET: [fix0] # <-- Add targets here!
        #TARGET: [x86-minimal] # <-- Add targets here!
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 100
        swap-size-mb: 200
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
        overprovision-lvm: 'true'
    - name: Setup env
      run: |

        echo "DT=$(date -d '+1 hour' +'%m-%d-%Y-%H-%M-%S')" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
        echo "$GITHUB_ENV"
    
    
    ### ONLY THIS RELEVANT FOR BUILDING ###
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: remove even more
      run: |
        sudo apt-get purge -y \
          '^llvm-.*' \
          'php.*' \
          '^mongodb-.*' \
          '^mysql-.*' \
          azure-cli \
          google-chrome-stable \
          firefox \
          powershell \
          microsoft-edge-stable \
          mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
    - name: dep
      run: sudo apt-get install -y unzip curl git qemu qemu-user-static binfmt-support
    - name: update e2fsprogs
      if: matrix.TARGET == 'x86-lunar'
      run: |
          git clone https://github.com/tytso/e2fsprogs
          cd e2fsprogs
          mkdir build
          cd build
          ../configure
          make
          sudo make install
    - name: Build Image
      run: |
        touch additionalFiles/issue-new.txt
        echo "OpenHD-image-${{ matrix.TARGET }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" > additionalFiles/issue-new.txt
        sudo ./build.sh ${{ matrix.TARGET }}
    # - name: debug
    #   run: |
    #     dd if=/dev/zero of=large_image.img bs=1M count=5650
    #     ls -a
    #     mkdir deploy
    #     mv *.img deploy/
    - name: remove old image to make space
      run: |
        sudo rm -Rf -v ./work-jetson-nano-2gb-bionic/03-Preconfiguration/*
        sudo rm -Rf -v ./work-jetson-nano-4gb-bionic/03-Preconfiguration/*
        sudo rm -Rf -v ./work-pi-bullseye/03-Preconfiguration/*
        sudo rm -Rf -v ./work-pi-legacy-bullseye/03-Preconfiguration/*
    - name: magic
      run: |
        ls -a
        sudo df -h
        sudo mv ./deploy/*.img ./OpenHD-image-${{ matrix.TARGET }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}.img
        echo "moved image"
        sudo rm -rvf deploy*
        sudo rm -rvf work*
        sudo rm -Rf /usr/share/doc
        sudo rm -Rf /home/linuxbrew
        sudo rm -Rf /home/runner-admin
        sudo rm -Rf /opt/hostedtoolcache
        sudo rm -Rf /opt/microsoft
        sudo rm -Rf /opt/hhvm
        sudo apt autoremove -y
        sudo df -h
        
    ########################################

    - name: Compose release filename
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      run: echo "artifact_name=OpenHD-image-${{ matrix.TARGET }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" >> $GITHUB_ENV
        
    - name: Pack image for ${{ matrix.TARGET }}
      uses: 'actions/upload-artifact@v4'
      with:
        name: "${{ matrix.TARGET }}-${{ env.DT }}"
        path: |
          *.img
          if-no-files-found: error