name: Image Release RPI

on: 
  push:
    paths-ignore:
      - '**.md'
      - '**.asciidoc'
      - '.gitignore'
      - 'LICENSE'

#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-22.04
    
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      
    steps:
    - name: Setup env
      run: |
        echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
        
    ### ONLY THIS RELEVANT FOR BUILDING ###
    
    - name: Debug file
      run: |
        dd if=/dev/urandom of=random_data_file2 bs=2M count=1

    - name: R2 tests
      shell: bash
      env:
        aws_endpoint: "https://data.openhdfpv.org"
        aws_key_id: ${{ secrets.DATA_ACCESS }}
        aws_secret_access_key: ${{ secrets.DATA_KEY }}
        aws_s3_bucket: openhd-images
        AWS_EC2_METADATA_DISABLED: true
      run: |
        aws configure set aws_access_key_id $aws_key_id
        aws configure set aws_secret_access_key $aws_secret_access_key 
        aws s3 --endpoint-url $aws_endpoint rm --recursive s3://$aws_s3_bucket/Downloader/oldrelease
        aws s3 --endpoint-url $aws_endpoint sync s3://$aws_s3_bucket/Downloader/release s3://$aws_s3_bucket/Downloader/oldrelease
        aws s3 --endpoint-url $aws_endpoint rm --recursive s3://$aws_s3_bucket/Downloader/release
        aws s3 --endpoint-url $aws_endpoint cp random_data_file2 s3://$aws_s3_bucket/Downloader/release/random_data_file2 

    