name: Image Release RPI

on:
  push:
    branches: [ "2.3-evo", "2.3-evo-refactor" ]

  workflow_dispatch:

#  schedule:
#    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    runs-on: ubuntu-22.04
    
    strategy:
      fail-fast: false # Don't fail all if any of the jobs is failing
      matrix:
        TESTING: [release]
        TARGET: [pi-bullseye] # <-- Add targets here!

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - name: Setup env
      run: |
        echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
        echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
        
    ### ONLY THIS RELEVANT FOR BUILDING ###
    - uses: actions/checkout@v3
    - name: update
      run: sudo apt-get update
    - name: fix ci's
      run: sudo apt-mark hold grub-efi-amd64-signed
    - name: upgrade
      run: sudo apt-get upgrade -y
    - name: dep
      run: sudo apt-get install -y unzip curl git qemu qemu-user-static binfmt-support
    - name: Build Image
      run: | 
         sudo ./build.sh ${{ matrix.TARGET }} ${{ matrix.TESTING }}
    - name: remove old image to make space
      run: |
        sudo rm -Rf -v ./work-jetson-nano-2gb-bionic/03-Preconfiguration/*
        sudo rm -Rf -v ./work-jetson-nano-4gb-bionic/03-Preconfiguration/*
        sudo rm -Rf -v ./work-pi-bullseye/03-Preconfiguration/*
        sudo rm -Rf -v ./work-pi-legacy-bullseye/03-Preconfiguration/*
    - name: magic
      run: |
        ls -a
        sudo df -h
        sudo mv ./deploy/*.img ./OpenHD-image-${{ matrix.TARGET }}-${{ matrix.TESTING }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}-configurable.img
        echo "moved image"
        sudo rm -rvf deploy*
        sudo rm -rvf work*
        sudo rm -Rf /usr/share/doc
        sudo rm -Rf /home/linuxbrew
        sudo rm -Rf /home/runner-admin
        sudo rm -Rf /opt/hostedtoolcache
        sudo rm -Rf /opt/microsoft
        sudo rm -Rf /opt/hhvm
        sudo apt autoremove -y
        sudo df -h
        
    ########################################


    - name: Compose release filename
      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      run: echo "artifact_name=OpenHD-image-release-${{ matrix.TARGET }}-${{ matrix.TESTING }}-${{ matrix.DISTRO }}-${GITHUB_REF##*/}-${{ env.DT }}" >> $GITHUB_ENV
        
    - name: Pack image for ${{ matrix.TARGET }} ${{ matrix.TESTING }}
      uses: 'actions/upload-artifact@v2'
      with:
        name: "${{ env.artifact_name }}"
        path: |
          *.img
          if-no-files-found: error

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: "${{ env.artifact_name }}"
    
    - name: compress
      run: |
        ls -a
        cd OpenHD*
        sha256sum * | cut -f 1 -d " " > ../sha256
        echo 'NAME<<EOF' >> $GITHUB_ENV
        ls -1 | sed -e 's/.img/.img.xz/g' >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        echo 'SIZEFULL<<EOF' >> $GITHUB_ENV
        wc -c *.img | cut -f 1 -d " " >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
        xz -v7T0 *.img
        ls -a
        mv * ../
        ls -a
    - name: debug
      run: |
        echo "${{ env.NAME }}"    

    - name: Upload to R2
      shell: bash
      env:
        aws_endpoint: "https://data.openhdfpv.org"
        aws_key_id: ${{ secrets.DATA_ACCESS }}
        aws_secret_access_key: ${{ secrets.DATA_KEY }}
        aws_s3_bucket: openhd-images
        AWS_EC2_METADATA_DISABLED: true
      run: |
        aws configure set aws_access_key_id $aws_key_id
        aws configure set aws_secret_access_key $aws_secret_access_key 
        aws s3 --endpoint-url $aws_endpoint cp ${{ env.NAME }} s3://$aws_s3_bucket/Downloader/release/${{ env.NAME }}

    - name: Download json
      run: curl https://data.openhdfpv.org/openhd-images/Downloader/os_list_imagingutility_v3_template.json -o os_list_imagingutility_v3_rpi.json -s

    - name: update json for the ImageWriter
      run: |
        ls -a      
        export NAME=$(cat last.release)
        export FILESIZE=${{ env.SIZEFULL }}
        export FILENAME=${{ env.NAME }}
        export DOWNLOADSIZE=$(wc -c *.xz | cut -f 1 -d " ")
        export SUM=$(cat sha256)
        export RELEASEDATE=$(date +%Y-%m-%d)
        echo "$NAME" >> rpi_name.txt
        echo "$FILESIZE" >> rpi_FILESIZE.txt
        echo "$FILENAME" >> rpi_FILENAME.txt
        echo "$DOWNLOADSIZE" >> rpi_DOWNLOADSIZE.txt
        echo "$SUM" >> rpi_SUM.txt
        echo "$RELEASEDATE" >> rpi_RELEASEDATE.txt
        sed -i "s/RELEASENAMErpi/$NAME/ig" os_list_imagingutility_v3_rpi.json
        sed -i "s/FILENAMErpi/$FILENAME/ig" os_list_imagingutility_v3_rpi.json       
        sed -i "s/FILESIZErpi/$FILESIZE/ig" os_list_imagingutility_v3_rpi.json       
        sed -i "s/SHASUMrpi/$SUM/ig" os_list_imagingutility_v3_rpi.json       
        sed -i "s/DOWNLOADSIZErpi/$DOWNLOADSIZE/ig" os_list_imagingutility_v3_rpi.json        
        sed -i "s/RELEASEDATErpi/$RELEASEDATE/ig" os_list_imagingutility_v3_rpi.json 
        aws s3 --endpoint-url $aws_endpoint cp . s3://$aws_s3_bucket/Downloader/release/ --recursive --exclude "*" --include "*.txt"   

    - name: Debug
      run: cat os_list_imagingutility_v3_rpi.json
    - name: Upload to R2
      shell: bash
      env:
        aws_endpoint: "https://data.openhdfpv.org"
        aws_key_id: ${{ secrets.DATA_ACCESS }}
        aws_secret_access_key: ${{ secrets.DATA_KEY }}
        aws_s3_bucket: openhd-images
        AWS_EC2_METADATA_DISABLED: true
      run: |
        aws configure set aws_access_key_id $aws_key_id
        aws configure set aws_secret_access_key $aws_secret_access_key 
        aws s3 --endpoint-url $aws_endpoint cp os_list_imagingutility_v3_rpi.json s3://$aws_s3_bucket/Downloader/release/os_list_imagingutility_v3_rpi.json